In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/handwritten-digit-identification-b1/sample_submission.csv
/kaggle/input/handwritten-digit-identification-b1/train.csv
/kaggle/input/handwritten-digit-identification-b1/test.csv

In [2]:
train_df = pd.read_csv("/kaggle/input/handwritten-digit-identification-b1/train.csv",header=None)
test_df = pd.read_csv("/kaggle/input/handwritten-digit-identification-b1/test.csv",header=None)

# Exploring the train dataset

In [3]:
train_df.head()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,1,0,0,3,11,16,15,0,0,0,...,0,0,0,3,15,16,9,0,0,8
1,2,0,0,0,10,12,3,0,0,0,...,0,0,0,2,10,14,13,4,0,8
2,3,0,0,3,10,15,8,0,0,0,...,0,0,0,2,10,8,0,0,0,5
3,4,0,0,5,11,16,16,8,0,0,...,0,0,0,7,16,11,2,0,0,3
4,5,0,0,4,12,16,16,4,0,0,...,0,0,0,3,12,13,9,0,0,2

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 66 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1430 non-null   int64
 1   1       1430 non-null   int64
 2   2       1430 non-null   int64
 3   3       1430 non-null   int64
 4   4       1430 non-null   int64
 5   5       1430 non-null   int64
 6   6       1430 non-null   int64
 7   7       1430 non-null   int64
 8   8       1430 non-null   int64
 9   9       1430 non-null   int64
 10  10      1430 non-null   int64
 11  11      1430 non-null   int64
 12  12      1430 non-null   int64
 13  13      1430 non-null   int64
 14  14      1430 non-null   int64
 15  15      1430 non-null   int64
 16  16      1430 non-null   int64
 17  17      1430 non-null   int64
 18  18      1430 non-null   int64
 19  19      1430 non-null   int64
 20  20      1430 non-null   int64
 21  21      1430 non-null   int64
 22  22      1430 non-null   int64
 23  23      1430 non-null   int64
 24  24      1430 non-null   int64
 25  25      1430 non-null   int64
 26  26      1430 non-null   int64
 27  27      1430 non-null   int64
 28  28      1430 non-null   int64
 29  29      1430 non-null   int64
 30  30      1430 non-null   int64
 31  31      1430 non-null   int64
 32  32      1430 non-null   int64
 33  33      1430 non-null   int64
 34  34      1430 non-null   int64
 35  35      1430 non-null   int64
 36  36      1430 non-null   int64
 37  37      1430 non-null   int64
 38  38      1430 non-null   int64
 39  39      1430 non-null   int64
 40  40      1430 non-null   int64
 41  41      1430 non-null   int64
 42  42      1430 non-null   int64
 43  43      1430 non-null   int64
 44  44      1430 non-null   int64
 45  45      1430 non-null   int64
 46  46      1430 non-null   int64
 47  47      1430 non-null   int64
 48  48      1430 non-null   int64
 49  49      1430 non-null   int64
 50  50      1430 non-null   int64
 51  51      1430 non-null   int64
 52  52      1430 non-null   int64
 53  53      1430 non-null   int64
 54  54      1430 non-null   int64
 55  55      1430 non-null   int64
 56  56      1430 non-null   int64
 57  57      1430 non-null   int64
 58  58      1430 non-null   int64
 59  59      1430 non-null   int64
 60  60      1430 non-null   int64
 61  61      1430 non-null   int64
 62  62      1430 non-null   int64
 63  63      1430 non-null   int64
 64  64      1430 non-null   int64
 65  65      1430 non-null   int64
dtypes: int64(66)
memory usage: 737.5 KB

In [5]:
train_df.corr()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,1.000000,NaN,0.008903,-0.001754,-0.017995,-0.030914,0.015945,0.044846,0.054510,-0.011926,...,-0.002275,0.040148,0.029801,0.014152,0.011055,0.012931,-0.010683,-0.032393,-0.031146,-0.010639
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.008903,NaN,1.000000,0.557979,0.198268,-0.018590,0.058691,0.044911,-0.039600,0.011217,...,-0.048612,-0.008757,0.863131,0.551750,0.126708,-0.109226,-0.032176,0.020689,-0.046931,-0.034295
3,-0.001754,NaN,0.557979,1.000000,0.554284,-0.066626,0.051012,-0.005369,-0.069172,-0.014338,...,-0.022744,-0.029067,0.507513,0.938099,0.498569,-0.135383,-0.045633,0.056494,0.068915,-0.011391
4,-0.017995,NaN,0.198268,0.554284,1.000000,0.022656,-0.172272,-0.128427,-0.045502,0.031340,...,0.075513,-0.056196,0.163293,0.555792,0.758629,-0.084477,-0.052502,0.049125,0.091949,-0.015499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.012931,NaN,-0.109226,-0.135383,-0.084477,-0.108695,-0.357941,-0.380629,-0.170888,0.041133,...,0.103299,0.006714,-0.118742,-0.215024,0.059702,1.000000,0.617265,0.243840,0.106516,-0.202329
62,-0.010683,NaN,-0.032176,-0.045633,-0.052502,-0.216206,-0.282312,-0.311954,-0.145545,0.016442,...,0.265042,-0.003251,-0.044225,-0.098486,-0.083187,0.617265,1.000000,0.644005,0.268167,-0.095453
63,-0.032393,NaN,0.020689,0.056494,0.049125,-0.249504,-0.271703,-0.181502,-0.065714,-0.011102,...,0.503456,-0.013351,0.005082,0.017693,-0.000846,0.243840,0.644005,1.000000,0.634114,-0.131073
64,-0.031146,NaN,-0.046931,0.068915,0.091949,-0.211167,-0.167986,-0.084317,-0.026229,-0.010120,...,0.534365,-0.005329,-0.050247,0.020480,0.096996,0.106516,0.268167,0.634114,1.000000,-0.189166
65,-0.010639,NaN,-0.034295,-0.011391,-0.015499,0.123533,0.211022,0.206670,0.104707,0.038025,...,-0.100559,-0.023398,-0.041046,0.011051,-0.020918,-0.202329,-0.095453,-0.131073,-0.189166,1.000000

### Dropping column 2 as it has no correlation

In [6]:
train_df.drop([0,1],axis='columns',inplace=True)

In [7]:
train_df.head()

,2,3,4,5,6,7,8,9,10,11,...,56,57,58,59,60,61,62,63,64,65
0,0,3,11,16,15,0,0,0,0,15,...,0,0,0,3,15,16,9,0,0,8
1,0,0,10,12,3,0,0,0,0,8,...,0,0,0,2,10,14,13,4,0,8
2,0,3,10,15,8,0,0,0,0,12,...,0,0,0,2,10,8,0,0,0,5
3,0,5,11,16,16,8,0,0,0,15,...,0,0,0,7,16,11,2,0,0,3
4,0,4,12,16,16,4,0,0,0,9,...,0,0,0,3,12,13,9,0,0,2

In [8]:
train_df

,2,3,4,5,6,7,8,9,10,11,...,56,57,58,59,60,61,62,63,64,65
0,0,3,11,16,15,0,0,0,0,15,...,0,0,0,3,15,16,9,0,0,8
1,0,0,10,12,3,0,0,0,0,8,...,0,0,0,2,10,14,13,4,0,8
2,0,3,10,15,8,0,0,0,0,12,...,0,0,0,2,10,8,0,0,0,5
3,0,5,11,16,16,8,0,0,0,15,...,0,0,0,7,16,11,2,0,0,3
4,0,4,12,16,16,4,0,0,0,9,...,0,0,0,3,12,13,9,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1425,0,0,1,7,14,14,0,0,0,3,...,0,0,0,0,0,7,12,0,0,9
1426,0,6,14,10,0,0,0,0,6,16,...,0,0,0,9,15,8,0,0,0,3
1427,0,8,16,15,6,0,0,0,5,14,...,0,0,0,8,15,16,14,1,0,8
1428,0,2,16,13,1,0,0,0,0,6,...,0,0,0,4,11,15,16,10,0,2
1429,0,7,12,15,6,0,0,0,14,16,...,0,0,0,7,16,7,0,0,0,5

In [9]:
X = train_df.drop([65],axis="columns")
y = train_df[65]

### Normalization is not required as all the data is in range.

## Splitting the data in 70:30 ratio

In [10]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,test_size=0.20, random_state=42)

# Tuning the model

In [11]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(256,128,64,32),random_state=40, max_iter=150, learning_rate_init=0.0013, 
                    activation='relu')
clf.fit(Xtrain,ytrain)

MLPClassifier(hidden_layer_sizes=(256, 128, 64, 32), learning_rate_init=0.0013,
              max_iter=150, random_state=40)

In [12]:
from sklearn.metrics import accuracy_score
preds = clf.predict(Xtest)
accuracy = accuracy_score(preds,ytest)
print("Accuracy on validation dataset",accuracy)

Accuracy on validation dataset 0.993006993006993

In [13]:
# from sklearn.neural_network import MLPClassifier
# clf = MLPClassifier(hidden_layer_sizes=(256,80,41,20),random_state=40, max_iter=150, learning_rate_init=0.001, 
#                     activation='logistic')
# clf.fit(Xtrain,ytrain)

In [14]:
# from sklearn.metrics import accuracy_score
# preds = clf.predict(Xtest)
# accuracy = accuracy_score(preds,ytest)
# print("Accuracy on validation dataset",accuracy)

# Exploring test dataset

In [15]:
test_df.head()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
0,1431,0,0,0,2,14,5,0,0,0,...,0,0,0,0,0,3,15,6,0,0
1,1432,0,0,0,13,12,0,0,0,0,...,12,0,0,0,1,10,16,14,4,0
2,1433,0,0,7,16,16,16,6,0,0,...,0,0,0,0,7,15,1,0,0,0
3,1434,0,2,15,15,6,0,0,0,0,...,1,0,0,3,15,14,11,2,0,0
4,1435,0,0,0,10,9,0,0,0,0,...,0,0,0,0,0,13,10,0,0,0

In [16]:
ID = test_df[0]
ID

0      1431
1      1432
2      1433
3      1434
4      1435
       ...
362    1793
363    1794
364    1795
365    1796
366    1797
Name: 0, Length: 367, dtype: int64

# Labelling the test dataset columns

In [17]:
test_df.drop([0,1],axis='columns',inplace=True)
test_df

,2,3,4,5,6,7,8,9,10,11,...,55,56,57,58,59,60,61,62,63,64
0,0,0,2,14,5,0,0,0,0,1,...,0,0,0,0,0,3,15,6,0,0
1,0,0,13,12,0,0,0,0,0,6,...,12,0,0,0,1,10,16,14,4,0
2,0,7,16,16,16,6,0,0,0,12,...,0,0,0,0,7,15,1,0,0,0
3,2,15,15,6,0,0,0,0,0,10,...,1,0,0,3,15,14,11,2,0,0
4,0,0,10,9,0,0,0,0,0,3,...,0,0,0,0,0,13,10,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,0,0,9,13,0,0,0,0,0,2,...,0,0,0,0,0,9,15,2,0,0
363,0,0,11,13,5,0,0,0,0,3,...,4,0,0,0,1,10,16,11,1,0
364,0,2,9,14,12,0,0,0,0,12,...,3,0,0,0,1,12,16,8,0,0
365,0,2,14,10,0,0,0,0,0,12,...,15,0,0,0,2,11,16,15,5,0
366,2,15,16,16,14,2,0,0,3,16,...,0,0,0,3,16,13,1,0,0,0

In [18]:
test_preds = clf.predict(test_df)
output = pd.DataFrame({"ID":ID,"Category":test_preds})
output.to_csv('submission.csv',index=False)
print(output)

       ID  Category
0    1431         4
1    1432         6
2    1433         5
3    1434         3
4    1435         4
..    ...       ...
362  1793         4
363  1794         6
364  1795         0
365  1796         6
366  1797         5

[367 rows x 2 columns]